<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NPOI" Version="2.7.5" />
    <PackageReference Include="PDFsharp" Version="6.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\InventoryManagement.Core\InventoryManagement.Core.csproj" />
    <ProjectReference Include="..\InventoryManagement.Infrastructure\InventoryManagement.Infrastructure.csproj" />
  </ItemGroup>

</Project>